apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laralog-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path