apiVersion: v1
kind: PersistentVolume
metadata:
  name: laralog-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /cdr/laralog
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path